import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import {CrudAnswerInterceptor} from './common/interceptors/crud-answer.interceptor';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';


async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.enableCors();
  app.useGlobalInterceptors(new CrudAnswerInterceptor());

  const swaggerConfig = new DocumentBuilder()
    .setTitle('Tr3butor API')
    .setDescription('Autogenerated tr3butor API')
    .setVersion('1.0')
    //.addTag('cats')
    .build();
  const document = SwaggerModule.createDocument(app, swaggerConfig);
  SwaggerModule.setup('api', app, document);

  await app.listen(3001);
}
bootstrap();
